WCSCoavBundle\Entity\Reservation:
    type: entity
    table: null
    repositoryClass: WCSCoavBundle\Repository\ReservationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nbSeats:
            type: integer

    manyToOne:
        flight:
            targetEntity: WCSCoavBundle\Entity\Flight

    manyToMany:
        User:
            targetEntity: WCSCoavBundle\Entity\User
